### ISSUE TITLE
can pass user/password from code ?

### ISSUE THREAD

**Issue by angga1992** [mycurelabs/vue-jitsi-meet#3]
I have a platform that create a room in a self-hosted Jitsi using prosody’s “Internal_plain” authentication.

So, the user that I configured works perfectly when I create a room out of my platform (It question the user/pass and when I put, entry).

But now I want that when I create a room from my platform, I want to pass the user/password automatically. In this way, the host would automatically enter while waiting for the other guests.

It’s possible?

**Comment by vesper8** [comment]
I would like to do the same, to have users auto-join with provided credentials. Did you ever figure it out?

**Comment by jofftiquez** [comment]
Hi @angga1992 I believe you can use the `executeCommand` to do this, I haven't tried this myself by please check this doc from Jitsi, thanks https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands#password

**Comment by jofftiquez** [comment]
Closing this for now due to the length of the opening of the issue. Apologies I haven't seen this one for a long time. 😅
