### ISSUE TITLE
WaterMarks still shows.

### ISSUE THREAD

**Issue by uwejan** [mycurelabs/vue-jitsi-meet#4]
The meeting starts successfully but the options has no effects.
```
         SHOW_JITSI_WATERMARK: false,
          SHOW_WATERMARK_FOR_GUESTS: false,
          SHOW_CHROME_EXTENSION_BANNER: false
```

**Comment by vesper8** [comment]
If I understand correctly you can only hide the logo if you self-host, if you use meet.jit.si then you are not allowed (and are literally not able) to hide the logo
